### ISSUE TITLE
missing use_mtee in unix default config

### ISSUE THREAD

**Issue by hmoffatt** [FirebirdSQL/oltp-emul#2]
I'm running the sh script on Linux and it's complaining

```
##########################################################
At least one variable: >>>use_mtee<<< - is NOT defined.
Check config file ./oltp25_config.nix.
##########################################################
```

The win.default config files say this variable is Windows only, but it looks like the UNIX script is still checking for it. I added use_mtee=0 to the config and it's working now.

**Comment by pavel-zotov** [comment]
Thank you, Hammish.
I will fix this soon.

**Comment by pavel-zotov** [comment]
Fix committed (together with replacement of $fbc/isql with $isql_name).
Please check again.

Thank you.

**Comment by hmoffatt** [comment]
Thanks, it's working for me now. Can you please add execute permission on the main script `1run_oltp_emul.sh` also?

**Comment by pavel-zotov** [comment]
Done.

git update-index --chmod=+x 1run_oltp_emul.sh
git ls-files --stage | findstr /i /c:1run_oltp_emul.sh
100755 3e905dfee770ab17157bdff0c35e09f12e2e3661 0       1run_oltp_emul.sh

**Comment by hmoffatt** [comment]
Thanks, all working for me now on Debian Linux.
